/*****************************************************************************************
**          Copyright(c) 2015-2025 MicroStrain by HBK. All rights reserved.             **
**                                                                                      **
**    MIT Licensed. See the included LICENSE file for a copy of the full MIT License.   **
*****************************************************************************************/

//Note: You can include this header file to include all of the headers for the public interface.

#pragma once

#include "mscl/stdafx.h"

#include "mscl/Bin.h"
#include "mscl/BitMask.h"
#include "mscl/Endianness.h"
#include "mscl/Exceptions.h"
#include "mscl/HighResClock.h"
#include "mscl/Histogram.h"
#include "mscl/LibVersion.h"
#include "mscl/ScopeHelper.h"
#include "mscl/simple_any.h"
#include "mscl/TimedCondition.h"
#include "mscl/TimeSpan.h"
#include "mscl/Timestamp.h"
#include "mscl/TimestampCounter.h"
#include "mscl/Types.h"
#include "mscl/Utils.h"
#include "mscl/Value.h"
#include "mscl/Version.h"

#if defined _WIN32
#include "mscl/Utils_Win32.h"
#include "mscl/WMI_Helper.h"
#endif // _WIN32

#include "mscl/Communication/BoostCommunication.h"
#include "mscl/Communication/Connection.h"
#include "mscl/Communication/ConnectionDebugData.h"
#include "mscl/Communication/Connection_Impl.h"
#include "mscl/Communication/Devices.h"
#include "mscl/Communication/MockConnection.h"
#include "mscl/Communication/NativeSerialPort.h"
#include "mscl/Communication/OperatingSystemErrorCodes.h"
#include "mscl/Communication/RawBytePacket.h"
#include "mscl/Communication/RawBytePacketCollector.h"
#include "mscl/Communication/SerialConnection.h"
#include "mscl/Communication/TcpIpConnection.h"

#ifdef MSCL_WITH_WEBSOCKETS
#include "mscl/Communication/WebSocketConnection.h"
#ifdef MSCL_WITH_SSL
#include "mscl/Communication/WebSocketSecureConnection.h"
#endif // MSCL_WITH_SSL
#endif // MSCL_WITH_WEBSOCKETS

#if defined _WIN32
#include "mscl/Communication/UpnpDeviceFinderCallback.h"
#include "mscl/Communication/UpnpService.h"
#include "mscl/Communication/WsdaFinder.h"
#elif defined __linux__
#include "mscl/Communication/UnixSocketConnection.h"
#endif // _WIN32

#include "mscl/MicroStrain/Bitfield.h"
#include "mscl/MicroStrain/ByteStream.h"
#include "mscl/MicroStrain/ChecksumBuilder.h"
#include "mscl/MicroStrain/DataBuffer.h"
#include "mscl/MicroStrain/DataPoint.h"
#include "mscl/MicroStrain/LinearEquation.h"
#include "mscl/MicroStrain/Matrix.h"
#include "mscl/MicroStrain/ResponseCollector.h"
#include "mscl/MicroStrain/ResponsePattern.h"
#include "mscl/MicroStrain/SampleRate.h"
#include "mscl/MicroStrain/SampleUtils.h"
#include "mscl/MicroStrain/Vector.h"

#include "mscl/MicroStrain/Displacement/DisplacementModels.h"
#include "mscl/MicroStrain/Displacement/DisplacementNode.h"

#include "mscl/MicroStrain/Displacement/Commands/DeviceTime.h"
#include "mscl/MicroStrain/Displacement/Commands/DisplacementOutputDataRate.h"
#include "mscl/MicroStrain/Displacement/Commands/GetAnalogToDisplacementCals.h"

#include "mscl/MicroStrain/Inertial/EulerAngles.h"
#include "mscl/MicroStrain/Inertial/ExposedInertialTypes.h"
#include "mscl/MicroStrain/Inertial/InertialNode.h"
#include "mscl/MicroStrain/Inertial/PositionVelocity.h"

#include "mscl/MicroStrain/Inertial/Commands/AccelBias.h"
#include "mscl/MicroStrain/Inertial/Commands/AdaptiveMeasurement.h"
#include "mscl/MicroStrain/Inertial/Commands/AdvancedLowPassFilterSettings.h"
#include "mscl/MicroStrain/Inertial/Commands/CaptureGyroBias.h"
#include "mscl/MicroStrain/Inertial/Commands/ComplementaryFilterSettings.h"
#include "mscl/MicroStrain/Inertial/Commands/ConingAndScullingEnable.h"
#include "mscl/MicroStrain/Inertial/Commands/ContinuousDataStream.h"
#include "mscl/MicroStrain/Inertial/Commands/DeviceStartupSettings.h"
#include "mscl/MicroStrain/Inertial/Commands/DeviceStatus.h"
#include "mscl/MicroStrain/Inertial/Commands/EstFilter_Commands.h"
#include "mscl/MicroStrain/Inertial/Commands/EstimationControlFlags.h"
#include "mscl/MicroStrain/Inertial/Commands/ExternalGNSSUpdate.h"
#include "mscl/MicroStrain/Inertial/Commands/ExternalHeadingUpdate.h"
#include "mscl/MicroStrain/Inertial/Commands/ExternalHeadingUpdateWithTimestamp.h"
#include "mscl/MicroStrain/Inertial/Commands/FilterInitializationConfig.h"
#include "mscl/MicroStrain/Inertial/Commands/FloatCommand.h"
#include "mscl/MicroStrain/Inertial/Commands/GeographicSource.h"
#include "mscl/MicroStrain/Inertial/Commands/GeometricVectorCommand.h"
#include "mscl/MicroStrain/Inertial/Commands/GNSS_AssistedFixControl.h"
#include "mscl/MicroStrain/Inertial/Commands/GNSS_AssistTimeUpdate.h"
#include "mscl/MicroStrain/Inertial/Commands/GNSS_Commands.h"
#include "mscl/MicroStrain/Inertial/Commands/GNSS_ConstellationSettings.h"
#include "mscl/MicroStrain/Inertial/Commands/GNSS_SBASSettings.h"
#include "mscl/MicroStrain/Inertial/Commands/GNSS_SourceControl.h"
#include "mscl/MicroStrain/Inertial/Commands/GyroBias.h"
#include "mscl/MicroStrain/Inertial/Commands/HeadingUpdateControl.h"
#include "mscl/MicroStrain/Inertial/Commands/MagnetometerCaptureAutoCalibration.h"
#include "mscl/MicroStrain/Inertial/Commands/MagnetometerHardIronOffset.h"
#include "mscl/MicroStrain/Inertial/Commands/MagnetometerSoftIronMatrix.h"
#include "mscl/MicroStrain/Inertial/Commands/Matrix3x3Command.h"
#include "mscl/MicroStrain/Inertial/Commands/PollData.h"
#include "mscl/MicroStrain/Inertial/Commands/RawRTCM_2_3Message.h"
#include "mscl/MicroStrain/Inertial/Commands/Sensor_Commands.h"
#include "mscl/MicroStrain/Inertial/Commands/SetReferencePosition.h"
#include "mscl/MicroStrain/Inertial/Commands/SignalConditioningSettings.h"
#include "mscl/MicroStrain/Inertial/Commands/System_Commands.h"
#include "mscl/MicroStrain/Inertial/Commands/UARTBaudRate.h"
#include "mscl/MicroStrain/Inertial/Commands/Uint16Command.h"
#include "mscl/MicroStrain/Inertial/Commands/Uint8Command.h"
#include "mscl/MicroStrain/Inertial/Commands/VehicleDynamicsMode.h"

#include "mscl/MicroStrain/Inertial/Packets/InertialFieldParser_EstFilter.h"
#include "mscl/MicroStrain/Inertial/Packets/InertialFieldParser_GNSS.h"
#include "mscl/MicroStrain/Inertial/Packets/InertialFieldParser_Sensor.h"
#include "mscl/MicroStrain/Inertial/Packets/InertialFieldParser_Shared.h"
#include "mscl/MicroStrain/Inertial/Packets/InertialFieldParser_System.h"

#include "mscl/MicroStrain/MIP/MipBuiltInTest.h"
#include "mscl/MicroStrain/MIP/MipChannel.h"
#include "mscl/MicroStrain/MIP/MipDataField.h"
#include "mscl/MicroStrain/MIP/MipDataPoint.h"
#include "mscl/MicroStrain/MIP/MipModels.h"
#include "mscl/MicroStrain/MIP/MipNode.h"
#include "mscl/MicroStrain/MIP/MipNodeFeatures.h"
#include "mscl/MicroStrain/MIP/MipNodeInfo.h"
#include "mscl/MicroStrain/MIP/MipNode_Impl.h"
#include "mscl/MicroStrain/MIP/MipParser.h"
#include "mscl/MicroStrain/MIP/MipTypes.h"

#include "mscl/MicroStrain/MIP/Commands/CyclePower.h"
#include "mscl/MicroStrain/MIP/Commands/GenericMipCommand.h"
#include "mscl/MicroStrain/MIP/Commands/GetDeviceDescriptorSets.h"
#include "mscl/MicroStrain/MIP/Commands/GetDeviceInfo.h"
#include "mscl/MicroStrain/MIP/Commands/GetExtendedDeviceDescriptorSets.h"
#include "mscl/MicroStrain/MIP/Commands/GPSTimeUpdate.h"
#include "mscl/MicroStrain/MIP/Commands/MipCmdResponse.h"
#include "mscl/MicroStrain/MIP/Commands/MipCommand.h"
#include "mscl/MicroStrain/MIP/Commands/MIP_Commands.h"
#include "mscl/MicroStrain/MIP/Commands/Mip_SetToIdle.h"
#include "mscl/MicroStrain/MIP/Commands/Ping.h"
#include "mscl/MicroStrain/MIP/Commands/Resume.h"

#include "mscl/MicroStrain/MIP/Packets/MipDataPacket.h"
#include "mscl/MicroStrain/MIP/Packets/MipFieldParser.h"
#include "mscl/MicroStrain/MIP/Packets/MipFieldParser_Displacement.h"
#include "mscl/MicroStrain/MIP/Packets/MipPacket.h"
#include "mscl/MicroStrain/MIP/Packets/MipPacketBuilder.h"
#include "mscl/MicroStrain/MIP/Packets/MipPacketCollector.h"
#include "mscl/MicroStrain/MIP/Packets/MipSharedDataFields.h"

#include "mscl/MicroStrain/RTK/RTKNode.h"

#include "mscl/MicroStrain/RTK/Commands/ActivationCode.h"
#include "mscl/MicroStrain/RTK/Commands/DeviceStatusFlags.h"

#include "mscl/MicroStrain/Wireless/ArmedDataloggingNetwork.h"
#include "mscl/MicroStrain/Wireless/BaseStation.h"
#include "mscl/MicroStrain/Wireless/BaseStationAnalogPair.h"
#include "mscl/MicroStrain/Wireless/BaseStationButton.h"
#include "mscl/MicroStrain/Wireless/BaseStationInfo.h"
#include "mscl/MicroStrain/Wireless/BaseStation_Impl.h"
#include "mscl/MicroStrain/Wireless/CalCoefficients.h"
#include "mscl/MicroStrain/Wireless/ChannelMask.h"
#include "mscl/MicroStrain/Wireless/DatalogDownloader.h"
#include "mscl/MicroStrain/Wireless/DataSweep.h"
#include "mscl/MicroStrain/Wireless/DeliveryStopFlags.h"
#include "mscl/MicroStrain/Wireless/LoggedDataSweep.h"
#include "mscl/MicroStrain/Wireless/MockBaseStation_Impl.h"
#include "mscl/MicroStrain/Wireless/MockWirelessNode_Impl.h"
#include "mscl/MicroStrain/Wireless/NodeCommTimes.h"
#include "mscl/MicroStrain/Wireless/NodeDiscovery.h"
#include "mscl/MicroStrain/Wireless/NodeMemory.h"
#include "mscl/MicroStrain/Wireless/NodeMemory_v1.h"
#include "mscl/MicroStrain/Wireless/NodeMemory_v2.h"
#include "mscl/MicroStrain/Wireless/RadioFeatures.h"
#include "mscl/MicroStrain/Wireless/StructuralHealth.h"
#include "mscl/MicroStrain/Wireless/SyncNetworkInfo.h"
#include "mscl/MicroStrain/Wireless/SyncSamplingFormulas.h"
#include "mscl/MicroStrain/Wireless/SyncSamplingNetwork.h"
#include "mscl/MicroStrain/Wireless/WirelessChannel.h"
#include "mscl/MicroStrain/Wireless/WirelessDataPoint.h"
#include "mscl/MicroStrain/Wireless/WirelessModels.h"
#include "mscl/MicroStrain/Wireless/WirelessNode.h"
#include "mscl/MicroStrain/Wireless/WirelessNode_Impl.h"
#include "mscl/MicroStrain/Wireless/WirelessParser.h"
#include "mscl/MicroStrain/Wireless/WirelessTypes.h"

#include "mscl/MicroStrain/Wireless/Commands/ArmForDatalogging.h"
#include "mscl/MicroStrain/Wireless/Commands/AutoBalance.h"
#include "mscl/MicroStrain/Wireless/Commands/AutoBalanceResult.h"
#include "mscl/MicroStrain/Wireless/Commands/AutoBalance_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/AutoCal.h"
#include "mscl/MicroStrain/Wireless/Commands/AutoCalInfo.h"
#include "mscl/MicroStrain/Wireless/Commands/AutoCalResult.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_BeaconStatus.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_Ping.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_Ping_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_ReadEeprom.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_ReadEeprom_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_Reset_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_RfSweepStart.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_SetBeacon.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_SetBeacon_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_WriteEeprom.h"
#include "mscl/MicroStrain/Wireless/Commands/BaseStation_WriteEeprom_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/BatchEepromRead.h"
#include "mscl/MicroStrain/Wireless/Commands/BeaconStatus.h"
#include "mscl/MicroStrain/Wireless/Commands/DatalogSessionInfoResult.h"
#include "mscl/MicroStrain/Wireless/Commands/Erase.h"
#include "mscl/MicroStrain/Wireless/Commands/Erase_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/GetDatalogSessionInfo.h"
#include "mscl/MicroStrain/Wireless/Commands/GetDiagnosticInfo.h"
#include "mscl/MicroStrain/Wireless/Commands/GetLoggedData.h"
#include "mscl/MicroStrain/Wireless/Commands/LongPing.h"
#include "mscl/MicroStrain/Wireless/Commands/PageDownload.h"
#include "mscl/MicroStrain/Wireless/Commands/PingResponse.h"
#include "mscl/MicroStrain/Wireless/Commands/Poll.h"
#include "mscl/MicroStrain/Wireless/Commands/ReadEeprom.h"
#include "mscl/MicroStrain/Wireless/Commands/ReadEeprom_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/ReadSingleSensor.h"
#include "mscl/MicroStrain/Wireless/Commands/Reset_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/SetToIdle.h"
#include "mscl/MicroStrain/Wireless/Commands/SetToIdleStatus.h"
#include "mscl/MicroStrain/Wireless/Commands/SetToIdle_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/Sleep.h"
#include "mscl/MicroStrain/Wireless/Commands/Sleep_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/StartNonSyncSampling.h"
#include "mscl/MicroStrain/Wireless/Commands/StartNonSyncSampling_v2.h"
#include "mscl/MicroStrain/Wireless/Commands/StartSyncSampling.h"
#include "mscl/MicroStrain/Wireless/Commands/TestNodeCommProtocol.h"
#include "mscl/MicroStrain/Wireless/Commands/TriggerArmedDatalogging.h"
#include "mscl/MicroStrain/Wireless/Commands/WirelessProtocol.h"
#include "mscl/MicroStrain/Wireless/Commands/WirelessResponsePattern.h"
#include "mscl/MicroStrain/Wireless/Commands/WriteEeprom.h"
#include "mscl/MicroStrain/Wireless/Commands/WriteEeprom_v2.h"

#include "mscl/MicroStrain/Wireless/Configuration/ActivitySense.h"
#include "mscl/MicroStrain/Wireless/Configuration/BaseStationConfig.h"
#include "mscl/MicroStrain/Wireless/Configuration/BaseStationEeprom.h"
#include "mscl/MicroStrain/Wireless/Configuration/BaseStationEepromHelper.h"
#include "mscl/MicroStrain/Wireless/Configuration/BaseStationEepromMap.h"
#include "mscl/MicroStrain/Wireless/Configuration/ConfigIssue.h"
#include "mscl/MicroStrain/Wireless/Configuration/DataModeMask.h"
#include "mscl/MicroStrain/Wireless/Configuration/Eeprom.h"
#include "mscl/MicroStrain/Wireless/Configuration/EepromLocation.h"
#include "mscl/MicroStrain/Wireless/Configuration/EventTriggerOptions.h"
#include "mscl/MicroStrain/Wireless/Configuration/FatigueOptions.h"
#include "mscl/MicroStrain/Wireless/Configuration/HistogramOptions.h"
#include "mscl/MicroStrain/Wireless/Configuration/InputRange.h"
#include "mscl/MicroStrain/Wireless/Configuration/MockNodeEeprom.h"
#include "mscl/MicroStrain/Wireless/Configuration/NodeEeprom.h"
#include "mscl/MicroStrain/Wireless/Configuration/NodeEepromHelper.h"
#include "mscl/MicroStrain/Wireless/Configuration/NodeEepromMap.h"
#include "mscl/MicroStrain/Wireless/Configuration/SyncNodeConfig.h"
#include "mscl/MicroStrain/Wireless/Configuration/TempSensorOptions.h"
#include "mscl/MicroStrain/Wireless/Configuration/WirelessNodeConfig.h"

#include "mscl/MicroStrain/Wireless/Features/AvailableSampleRates.h"
#include "mscl/MicroStrain/Wireless/Features/AvailableTransmitPowers.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures_analog.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures_rs232.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures_usb.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures_usb200.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures_wsda.h"
#include "mscl/MicroStrain/Wireless/Features/BaseStationFeatures_wsda2000.h"
#include "mscl/MicroStrain/Wireless/Features/ChannelGroup.h"
#include "mscl/MicroStrain/Wireless/Features/FlashInfo.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_200series.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_cfBearingTempLink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_dvrtlink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_envlinkMini.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_envlinkPro.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_glink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_glink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_glink200r.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_glink2External.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_glink2Internal.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_iepeLink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_ptlink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_rtdlink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_rtdlink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglink200oem.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglinkMicro.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglinkoem.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglinkoemHermetic.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglinkoemNoXR.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_sglinkrgd.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_shmlink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_shmlink2.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_shmlink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_shmlink201.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_shmlink201FullBridge.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_shmlink210.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_tclink1ch.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_tclink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_tclink200oem.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_tclink3ch.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_tclink6ch.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_torqueLink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_torqueLink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_torqueLink200_3ch.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_torqueLink200_3ch_s.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_vlink.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_vlink200.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_vlink_legacy.h"
#include "mscl/MicroStrain/Wireless/Features/NodeFeatures_wirelessImpactSensor.h"
#include "mscl/MicroStrain/Wireless/Features/NodeInfo.h"

#include "mscl/MicroStrain/Wireless/Packets/AsyncDigitalAnalogPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/AsyncDigitalPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/BeaconEchoPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/BufferedLdcPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/BufferedLdcPacket_v2.h"
#include "mscl/MicroStrain/Wireless/Packets/DiagnosticPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/HclSmartBearing_CalPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/HclSmartBearing_RawPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/LdcMathPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/LdcMathPacket_aspp3.h"
#include "mscl/MicroStrain/Wireless/Packets/LdcPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/LdcPacket_v2.h"
#include "mscl/MicroStrain/Wireless/Packets/LdcPacket_v2_aspp3.h"
#include "mscl/MicroStrain/Wireless/Packets/NodeDiscoveryPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/NodeDiscoveryPacket_v2.h"
#include "mscl/MicroStrain/Wireless/Packets/NodeDiscoveryPacket_v3.h"
#include "mscl/MicroStrain/Wireless/Packets/NodeDiscoveryPacket_v4.h"
#include "mscl/MicroStrain/Wireless/Packets/NodeDiscoveryPacket_v5.h"
#include "mscl/MicroStrain/Wireless/Packets/RawAngleStrainPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/RfSweepPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/RollerPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/ShmPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/ShmPacket_v2_aspp3.h"
#include "mscl/MicroStrain/Wireless/Packets/SyncSamplingMathPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/SyncSamplingMathPacket_aspp3.h"
#include "mscl/MicroStrain/Wireless/Packets/SyncSamplingPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/SyncSamplingPacket_v2.h"
#include "mscl/MicroStrain/Wireless/Packets/SyncSamplingPacket_v2_aspp3.h"
#include "mscl/MicroStrain/Wireless/Packets/WirelessDataPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/WirelessPacket.h"
#include "mscl/MicroStrain/Wireless/Packets/WirelessPacketCollector.h"
#include "mscl/MicroStrain/Wireless/Packets/WirelessPacketUtils.h"
