//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.12
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public class ChannelCalMap : global::System.IDisposable 
    , global::System.Collections.Generic.IDictionary<WirelessChannel.ChannelId, CalCoefficients>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal ChannelCalMap(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ChannelCalMap obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~ChannelCalMap() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msclPINVOKE.delete_ChannelCalMap(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }


  public CalCoefficients this[WirelessChannel.ChannelId key] {
    get {
      return getitem(key);
    }

    set {
      setitem(key, value);
    }
  }

  public bool TryGetValue(WirelessChannel.ChannelId key, out CalCoefficients value) {
    if (this.ContainsKey(key)) {
      value = this[key];
      return true;
    }
    value = default(CalCoefficients);
    return false;
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsReadOnly {
    get { 
      return false; 
    }
  }

  public global::System.Collections.Generic.ICollection<WirelessChannel.ChannelId> Keys {
    get {
      global::System.Collections.Generic.ICollection<WirelessChannel.ChannelId> keys = new global::System.Collections.Generic.List<WirelessChannel.ChannelId>();
      int size = this.Count;
      if (size > 0) {
        global::System.IntPtr iter = create_iterator_begin();
        for (int i = 0; i < size; i++) {
          keys.Add(get_next_key(iter));
        }
        destroy_iterator(iter);
      }
      return keys;
    }
  }

  public global::System.Collections.Generic.ICollection<CalCoefficients> Values {
    get {
      global::System.Collections.Generic.ICollection<CalCoefficients> vals = new global::System.Collections.Generic.List<CalCoefficients>();
      foreach (global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients> pair in this) {
        vals.Add(pair.Value);
      }
      return vals;
    }
  }
  
  public void Add(global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients> item) {
    Add(item.Key, item.Value);
  }

  public bool Remove(global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients> item) {
    if (Contains(item)) {
      return Remove(item.Key);
    } else {
      return false;
    }
  }

  public bool Contains(global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients> item) {
    if (this[item.Key] == item.Value) {
      return true;
    } else {
      return false;
    }
  }

  public void CopyTo(global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>[] array) {
    CopyTo(array, 0);
  }

  public void CopyTo(global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>[] array, int arrayIndex) {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (arrayIndex+this.Count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");

    global::System.Collections.Generic.IList<WirelessChannel.ChannelId> keyList = new global::System.Collections.Generic.List<WirelessChannel.ChannelId>(this.Keys);
    for (int i = 0; i < keyList.Count; i++) {
      WirelessChannel.ChannelId currentKey = keyList[i];
      array.SetValue(new global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>(currentKey, this[currentKey]), arrayIndex+i);
    }
  }

  global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>>.GetEnumerator() {
    return new ChannelCalMapEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new ChannelCalMapEnumerator(this);
  }

  public ChannelCalMapEnumerator GetEnumerator() {
    return new ChannelCalMapEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class ChannelCalMapEnumerator : global::System.Collections.IEnumerator, 
      global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>>
  {
    private ChannelCalMap collectionRef;
    private global::System.Collections.Generic.IList<WirelessChannel.ChannelId> keyCollection;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public ChannelCalMapEnumerator(ChannelCalMap collection) {
      collectionRef = collection;
      keyCollection = new global::System.Collections.Generic.List<WirelessChannel.ChannelId>(collection.Keys);
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients> Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        WirelessChannel.ChannelId currentKey = keyCollection[currentIndex];
        currentObject = new global::System.Collections.Generic.KeyValuePair<WirelessChannel.ChannelId, CalCoefficients>(currentKey, collectionRef[currentKey]);
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }
  

  public ChannelCalMap() : this(msclPINVOKE.new_ChannelCalMap__SWIG_0(), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public ChannelCalMap(ChannelCalMap other) : this(msclPINVOKE.new_ChannelCalMap__SWIG_1(ChannelCalMap.getCPtr(other)), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = msclPINVOKE.ChannelCalMap_size(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool empty() {
    bool ret = msclPINVOKE.ChannelCalMap_empty(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Clear() {
    msclPINVOKE.ChannelCalMap_Clear(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  private CalCoefficients getitem(WirelessChannel.ChannelId key) {
    CalCoefficients ret = new CalCoefficients(msclPINVOKE.ChannelCalMap_getitem(swigCPtr, (int)key), false);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(WirelessChannel.ChannelId key, CalCoefficients x) {
    msclPINVOKE.ChannelCalMap_setitem(swigCPtr, (int)key, CalCoefficients.getCPtr(x));
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool ContainsKey(WirelessChannel.ChannelId key) {
    bool ret = msclPINVOKE.ChannelCalMap_ContainsKey(swigCPtr, (int)key);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Add(WirelessChannel.ChannelId key, CalCoefficients val) {
    msclPINVOKE.ChannelCalMap_Add(swigCPtr, (int)key, CalCoefficients.getCPtr(val));
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Remove(WirelessChannel.ChannelId key) {
    bool ret = msclPINVOKE.ChannelCalMap_Remove(swigCPtr, (int)key);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private global::System.IntPtr create_iterator_begin() {
    global::System.IntPtr ret = msclPINVOKE.ChannelCalMap_create_iterator_begin(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private WirelessChannel.ChannelId get_next_key(global::System.IntPtr swigiterator) {
    WirelessChannel.ChannelId ret = (WirelessChannel.ChannelId)msclPINVOKE.ChannelCalMap_get_next_key(swigCPtr, swigiterator);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void destroy_iterator(global::System.IntPtr swigiterator) {
    msclPINVOKE.ChannelCalMap_destroy_iterator(swigCPtr, swigiterator);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
