//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public class ContinuousBIT_IMU_General : Bitfield {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal ContinuousBIT_IMU_General(global::System.IntPtr cPtr, bool cMemoryOwn) : base(msclPINVOKE.ContinuousBIT_IMU_General_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(ContinuousBIT_IMU_General obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msclPINVOKE.delete_ContinuousBIT_IMU_General(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public byte flags() {
    byte ret = msclPINVOKE.ContinuousBIT_IMU_General_flags(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool clockFault() {
    bool ret = msclPINVOKE.ContinuousBIT_IMU_General_clockFault(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool communicationFault() {
    bool ret = msclPINVOKE.ContinuousBIT_IMU_General_communicationFault(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool timingOverrun() {
    bool ret = msclPINVOKE.ContinuousBIT_IMU_General_timingOverrun(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool calibrationErrorAccel() {
    bool ret = msclPINVOKE.ContinuousBIT_IMU_General_calibrationErrorAccel(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool calibrationErrorGyro() {
    bool ret = msclPINVOKE.ContinuousBIT_IMU_General_calibrationErrorGyro(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool calibrationErrorMag() {
    bool ret = msclPINVOKE.ContinuousBIT_IMU_General_calibrationErrorMag(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly byte CLOCK_FAULT = msclPINVOKE.ContinuousBIT_IMU_General_CLOCK_FAULT_get();
  public static readonly byte COMMUNICATION_FAULT = msclPINVOKE.ContinuousBIT_IMU_General_COMMUNICATION_FAULT_get();
  public static readonly byte TIMING_OVERRUN = msclPINVOKE.ContinuousBIT_IMU_General_TIMING_OVERRUN_get();
  public static readonly byte CALIBRATION_ERROR_ACCEL = msclPINVOKE.ContinuousBIT_IMU_General_CALIBRATION_ERROR_ACCEL_get();
  public static readonly byte CALIBRATION_ERROR_GYRO = msclPINVOKE.ContinuousBIT_IMU_General_CALIBRATION_ERROR_GYRO_get();
  public static readonly byte CALIBRATION_ERROR_MAG = msclPINVOKE.ContinuousBIT_IMU_General_CALIBRATION_ERROR_MAG_get();
}

}
