//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public class CV7ContinuousBIT_System : Bitfield {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;

  internal CV7ContinuousBIT_System(global::System.IntPtr cPtr, bool cMemoryOwn) : base(msclPINVOKE.CV7ContinuousBIT_System_SWIGUpcast(cPtr), cMemoryOwn) {
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(CV7ContinuousBIT_System obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  protected override void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msclPINVOKE.delete_CV7ContinuousBIT_System(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      base.Dispose(disposing);
    }
  }

  public CV7ContinuousBIT_System() : this(msclPINVOKE.new_CV7ContinuousBIT_System__SWIG_0(), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public CV7ContinuousBIT_System(uint bits) : this(msclPINVOKE.new_CV7ContinuousBIT_System__SWIG_1(bits), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public byte generalFlags() {
    byte ret = msclPINVOKE.CV7ContinuousBIT_System_generalFlags(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public byte processFlags() {
    byte ret = msclPINVOKE.CV7ContinuousBIT_System_processFlags(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool systemClockFailure() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_systemClockFailure(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool powerFault() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_powerFault(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool firmwareFault() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_firmwareFault(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool timingOverload() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_timingOverload(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool bufferOverrun() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_bufferOverrun(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool imuProcessFault() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_imuProcessFault(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool imuDataRateMismatch() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_imuDataRateMismatch(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool imuOverrunDroppedData() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_imuOverrunDroppedData(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool imuStuck() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_imuStuck(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool filterProcessFault() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_filterProcessFault(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool filterDroppedData() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_filterDroppedData(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool filterRateMismatch() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_filterRateMismatch(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool filterStuck() {
    bool ret = msclPINVOKE.CV7ContinuousBIT_System_filterStuck(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static readonly uint SYSTEM_CLOCK_FAILURE = msclPINVOKE.CV7ContinuousBIT_System_SYSTEM_CLOCK_FAILURE_get();
  public static readonly uint POWER_FAULT = msclPINVOKE.CV7ContinuousBIT_System_POWER_FAULT_get();
  public static readonly uint FIRMWARE_FAULT = msclPINVOKE.CV7ContinuousBIT_System_FIRMWARE_FAULT_get();
  public static readonly uint TIMING_OVERLOAD = msclPINVOKE.CV7ContinuousBIT_System_TIMING_OVERLOAD_get();
  public static readonly uint BUFFER_OVERRUN = msclPINVOKE.CV7ContinuousBIT_System_BUFFER_OVERRUN_get();
  public static readonly uint IMU_PROCESS_FAULT = msclPINVOKE.CV7ContinuousBIT_System_IMU_PROCESS_FAULT_get();
  public static readonly uint IMU_DATA_RATE_MISMATCH = msclPINVOKE.CV7ContinuousBIT_System_IMU_DATA_RATE_MISMATCH_get();
  public static readonly uint IMU_OVERRUN_DROPPED_DATA = msclPINVOKE.CV7ContinuousBIT_System_IMU_OVERRUN_DROPPED_DATA_get();
  public static readonly uint IMU_STUCK = msclPINVOKE.CV7ContinuousBIT_System_IMU_STUCK_get();
  public static readonly uint FILTER_PROCESS_FAULT = msclPINVOKE.CV7ContinuousBIT_System_FILTER_PROCESS_FAULT_get();
  public static readonly uint FILTER_DROPPED_DATA = msclPINVOKE.CV7ContinuousBIT_System_FILTER_DROPPED_DATA_get();
  public static readonly uint FILTER_RATE_MISMATCH = msclPINVOKE.CV7ContinuousBIT_System_FILTER_RATE_MISMATCH_get();
  public static readonly uint FILTER_STUCK = msclPINVOKE.CV7ContinuousBIT_System_FILTER_STUCK_get();
}

}
