//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 3.0.6
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public class DerivedChannelMasks : global::System.IDisposable 
    , global::System.Collections.Generic.IDictionary<WirelessTypes.DerivedCategory, ChannelMask>
 {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal DerivedChannelMasks(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(DerivedChannelMasks obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~DerivedChannelMasks() {
    Dispose();
  }

  public virtual void Dispose() {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msclPINVOKE.delete_DerivedChannelMasks(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
      global::System.GC.SuppressFinalize(this);
    }
  }


  public ChannelMask this[WirelessTypes.DerivedCategory key] {
    get {
      return getitem(key);
    }

    set {
      setitem(key, value);
    }
  }

  public bool TryGetValue(WirelessTypes.DerivedCategory key, out ChannelMask value) {
    if (this.ContainsKey(key)) {
      value = this[key];
      return true;
    }
    value = default(ChannelMask);
    return false;
  }

  public int Count {
    get {
      return (int)size();
    }
  }

  public bool IsReadOnly {
    get { 
      return false; 
    }
  }

  public global::System.Collections.Generic.ICollection<WirelessTypes.DerivedCategory> Keys {
    get {
      global::System.Collections.Generic.ICollection<WirelessTypes.DerivedCategory> keys = new global::System.Collections.Generic.List<WirelessTypes.DerivedCategory>();
      int size = this.Count;
      if (size > 0) {
        global::System.IntPtr iter = create_iterator_begin();
        for (int i = 0; i < size; i++) {
          keys.Add(get_next_key(iter));
        }
        destroy_iterator(iter);
      }
      return keys;
    }
  }

  public global::System.Collections.Generic.ICollection<ChannelMask> Values {
    get {
      global::System.Collections.Generic.ICollection<ChannelMask> vals = new global::System.Collections.Generic.List<ChannelMask>();
      foreach (global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask> pair in this) {
        vals.Add(pair.Value);
      }
      return vals;
    }
  }
  
  public void Add(global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask> item) {
    Add(item.Key, item.Value);
  }

  public bool Remove(global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask> item) {
    if (Contains(item)) {
      return Remove(item.Key);
    } else {
      return false;
    }
  }

  public bool Contains(global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask> item) {
    if (this[item.Key] == item.Value) {
      return true;
    } else {
      return false;
    }
  }

  public void CopyTo(global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>[] array) {
    CopyTo(array, 0);
  }

  public void CopyTo(global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>[] array, int arrayIndex) {
    if (array == null)
      throw new global::System.ArgumentNullException("array");
    if (arrayIndex < 0)
      throw new global::System.ArgumentOutOfRangeException("arrayIndex", "Value is less than zero");
    if (array.Rank > 1)
      throw new global::System.ArgumentException("Multi dimensional array.", "array");
    if (arrayIndex+this.Count > array.Length)
      throw new global::System.ArgumentException("Number of elements to copy is too large.");

    global::System.Collections.Generic.IList<WirelessTypes.DerivedCategory> keyList = new global::System.Collections.Generic.List<WirelessTypes.DerivedCategory>(this.Keys);
    for (int i = 0; i < keyList.Count; i++) {
      WirelessTypes.DerivedCategory currentKey = keyList[i];
      array.SetValue(new global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>(currentKey, this[currentKey]), arrayIndex+i);
    }
  }

  global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>> global::System.Collections.Generic.IEnumerable<global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>>.GetEnumerator() {
    return new DerivedChannelMasksEnumerator(this);
  }

  global::System.Collections.IEnumerator global::System.Collections.IEnumerable.GetEnumerator() {
    return new DerivedChannelMasksEnumerator(this);
  }

  public DerivedChannelMasksEnumerator GetEnumerator() {
    return new DerivedChannelMasksEnumerator(this);
  }

  // Type-safe enumerator
  /// Note that the IEnumerator documentation requires an InvalidOperationException to be thrown
  /// whenever the collection is modified. This has been done for changes in the size of the
  /// collection but not when one of the elements of the collection is modified as it is a bit
  /// tricky to detect unmanaged code that modifies the collection under our feet.
  public sealed class DerivedChannelMasksEnumerator : global::System.Collections.IEnumerator, 
      global::System.Collections.Generic.IEnumerator<global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>>
  {
    private DerivedChannelMasks collectionRef;
    private global::System.Collections.Generic.IList<WirelessTypes.DerivedCategory> keyCollection;
    private int currentIndex;
    private object currentObject;
    private int currentSize;

    public DerivedChannelMasksEnumerator(DerivedChannelMasks collection) {
      collectionRef = collection;
      keyCollection = new global::System.Collections.Generic.List<WirelessTypes.DerivedCategory>(collection.Keys);
      currentIndex = -1;
      currentObject = null;
      currentSize = collectionRef.Count;
    }

    // Type-safe iterator Current
    public global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask> Current {
      get {
        if (currentIndex == -1)
          throw new global::System.InvalidOperationException("Enumeration not started.");
        if (currentIndex > currentSize - 1)
          throw new global::System.InvalidOperationException("Enumeration finished.");
        if (currentObject == null)
          throw new global::System.InvalidOperationException("Collection modified.");
        return (global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>)currentObject;
      }
    }

    // Type-unsafe IEnumerator.Current
    object global::System.Collections.IEnumerator.Current {
      get {
        return Current;
      }
    }

    public bool MoveNext() {
      int size = collectionRef.Count;
      bool moveOkay = (currentIndex+1 < size) && (size == currentSize);
      if (moveOkay) {
        currentIndex++;
        WirelessTypes.DerivedCategory currentKey = keyCollection[currentIndex];
        currentObject = new global::System.Collections.Generic.KeyValuePair<WirelessTypes.DerivedCategory, ChannelMask>(currentKey, collectionRef[currentKey]);
      } else {
        currentObject = null;
      }
      return moveOkay;
    }

    public void Reset() {
      currentIndex = -1;
      currentObject = null;
      if (collectionRef.Count != currentSize) {
        throw new global::System.InvalidOperationException("Collection modified.");
      }
    }

    public void Dispose() {
      currentIndex = -1;
      currentObject = null;
    }
  }
  

  public DerivedChannelMasks() : this(msclPINVOKE.new_DerivedChannelMasks__SWIG_0(), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public DerivedChannelMasks(DerivedChannelMasks other) : this(msclPINVOKE.new_DerivedChannelMasks__SWIG_1(DerivedChannelMasks.getCPtr(other)), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  private uint size() {
    uint ret = msclPINVOKE.DerivedChannelMasks_size(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public bool empty() {
    bool ret = msclPINVOKE.DerivedChannelMasks_empty(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Clear() {
    msclPINVOKE.DerivedChannelMasks_Clear(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  private ChannelMask getitem(WirelessTypes.DerivedCategory key) {
    ChannelMask ret = new ChannelMask(msclPINVOKE.DerivedChannelMasks_getitem(swigCPtr, (int)key), false);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void setitem(WirelessTypes.DerivedCategory key, ChannelMask x) {
    msclPINVOKE.DerivedChannelMasks_setitem(swigCPtr, (int)key, ChannelMask.getCPtr(x));
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool ContainsKey(WirelessTypes.DerivedCategory key) {
    bool ret = msclPINVOKE.DerivedChannelMasks_ContainsKey(swigCPtr, (int)key);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public void Add(WirelessTypes.DerivedCategory key, ChannelMask val) {
    msclPINVOKE.DerivedChannelMasks_Add(swigCPtr, (int)key, ChannelMask.getCPtr(val));
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public bool Remove(WirelessTypes.DerivedCategory key) {
    bool ret = msclPINVOKE.DerivedChannelMasks_Remove(swigCPtr, (int)key);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private global::System.IntPtr create_iterator_begin() {
    global::System.IntPtr ret = msclPINVOKE.DerivedChannelMasks_create_iterator_begin(swigCPtr);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private WirelessTypes.DerivedCategory get_next_key(global::System.IntPtr swigiterator) {
    WirelessTypes.DerivedCategory ret = (WirelessTypes.DerivedCategory)msclPINVOKE.DerivedChannelMasks_get_next_key(swigCPtr, swigiterator);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  private void destroy_iterator(global::System.IntPtr swigiterator) {
    msclPINVOKE.DerivedChannelMasks_destroy_iterator(swigCPtr, swigiterator);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

}

}
