//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public enum EventControlMode {
  DISABLED = 0x00,
  ENABLED = 0x01,
  TEST = 0x02,
  TEST_PULSE = 0x03
}

}
