//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public enum GnssAidingStatus {
  GNSS_AIDING_TIGHT_COUPLING = 0x0001,
  GNSS_AIDING_DIFFERENTIAL = 0x0002,
  GNSS_AIDING_INTEGER_FIX = 0x0004,
  GNSS_AIDING_GPS = 0x0018,
  GNSS_AIDING_GLONASS = 0x0060,
  GNSS_AIDING_GALILEO = 0x0180,
  GNSS_AIDING_BEIDOU = 0x0600
}

}
