//------------------------------------------------------------------------------
// <auto-generated />
//
// This file was automatically generated by SWIG (http://www.swig.org).
// Version 4.0.0
//
// Do not make changes to this file unless you know what you are doing--modify
// the SWIG interface file instead.
//------------------------------------------------------------------------------

namespace mscl {

public class LowPassFilterData : global::System.IDisposable {
  private global::System.Runtime.InteropServices.HandleRef swigCPtr;
  protected bool swigCMemOwn;

  internal LowPassFilterData(global::System.IntPtr cPtr, bool cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = new global::System.Runtime.InteropServices.HandleRef(this, cPtr);
  }

  internal static global::System.Runtime.InteropServices.HandleRef getCPtr(LowPassFilterData obj) {
    return (obj == null) ? new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero) : obj.swigCPtr;
  }

  ~LowPassFilterData() {
    Dispose(false);
  }

  public void Dispose() {
    Dispose(true);
    global::System.GC.SuppressFinalize(this);
  }

  protected virtual void Dispose(bool disposing) {
    lock(this) {
      if (swigCPtr.Handle != global::System.IntPtr.Zero) {
        if (swigCMemOwn) {
          swigCMemOwn = false;
          msclPINVOKE.delete_LowPassFilterData(swigCPtr);
        }
        swigCPtr = new global::System.Runtime.InteropServices.HandleRef(null, global::System.IntPtr.Zero);
      }
    }
  }

  public LowPassFilterData() : this(msclPINVOKE.new_LowPassFilterData__SWIG_0(), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public LowPassFilterData(MipTypes.ChannelField descriptor) : this(msclPINVOKE.new_LowPassFilterData__SWIG_1((int)descriptor), true) {
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
  }

  public MipTypes.ChannelField dataDescriptor {
    set {
      msclPINVOKE.LowPassFilterData_dataDescriptor_set(swigCPtr, (int)value);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      MipTypes.ChannelField ret = (MipTypes.ChannelField)msclPINVOKE.LowPassFilterData_dataDescriptor_get(swigCPtr);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public LowPassFilterData.ManualFilterBandwidthConfig manualFilterBandwidthConfig {
    set {
      msclPINVOKE.LowPassFilterData_manualFilterBandwidthConfig_set(swigCPtr, (int)value);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      LowPassFilterData.ManualFilterBandwidthConfig ret = (LowPassFilterData.ManualFilterBandwidthConfig)msclPINVOKE.LowPassFilterData_manualFilterBandwidthConfig_get(swigCPtr);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public bool applyLowPassFilter {
    set {
      msclPINVOKE.LowPassFilterData_applyLowPassFilter_set(swigCPtr, value);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      bool ret = msclPINVOKE.LowPassFilterData_applyLowPassFilter_get(swigCPtr);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public float cutoffFrequency {
    set {
      msclPINVOKE.LowPassFilterData_cutoffFrequency_set(swigCPtr, value);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    } 
    get {
      float ret = msclPINVOKE.LowPassFilterData_cutoffFrequency_get(swigCPtr);
      if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
      return ret;
    } 
  }

  public static byte getDataDescriptorForCommand(MipTypes.ChannelField descriptor) {
    byte ret = msclPINVOKE.LowPassFilterData_getDataDescriptorForCommand((int)descriptor);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public static MipTypes.ChannelField getDataDescriptorFromUint8(byte descriptor) {
    MipTypes.ChannelField ret = (MipTypes.ChannelField)msclPINVOKE.LowPassFilterData_getDataDescriptorFromUint8(descriptor);
    if (msclPINVOKE.SWIGPendingException.Pending) throw msclPINVOKE.SWIGPendingException.Retrieve();
    return ret;
  }

  public enum ManualFilterBandwidthConfig {
    SET_TO_HALF_REPORTING_RATE = 0x00,
    USER_SPECIFIED_CUTOFF_FREQ = 0x01
  }

}

}
