name: Close all issues

on:
  workflow_dispatch:
    branches:
      -master

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@v9
        with:
          days-before-issue-close: 0
          days-before-issue-stale: 0
          close-issue-message: 'Our issue tracking has moved! If you are still experiencing issues with MSCL please open a ticket on the [MicroStrain Support Portal](https://support.microstrain.com/)'
